# Prometheus Configuration for VMware Aria Operations Exporter

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vmware-aria-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # VMware Aria Operations Exporter
  - job_name: 'vmware-aria-operations'
    static_configs:
      - targets: ['vmware-aria-exporter:8000']
    scrape_interval: 60s  # Scrape every minute
    scrape_timeout: 30s   # Timeout after 30 seconds
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # Optional: Node Exporter for system metrics
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 15s

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Remote write configuration (optional)
# remote_write:
#   - url: "http://remote-storage:9201/write"

# Remote read configuration (optional)
# remote_read:
#   - url: "http://remote-storage:9201/read"